### PR TITLE
Fabio | Feature | PgBouncer service

### PR DESCRIPTION
**Pull request by codeagencybe**
Added base work for pgbouncer service 

Updates files:
.env.example
docker-compose.override.local.yml
docker-compose.override.production.yml
docker-compose.yml
pgbouncer/docker-entrypoint-initdb.d/init.sh

To check:
- make sure ports are updated so Odoo/apps connect through pgbouncer instead of direct
- make it optional to use pgbouncer? I have added it as service with default false, but feel free to change

### CODE REVIEW

**Comment by bosd** [comment]
@yhaelopez Can you please review?

**Comment by ppsaheed** [comment]
He is not responding

**Comment by yhaelopez** [comment]
After a long disappreance period (due to personal & professional matters) I'm getting back on track.
I'll complete this integration and let you know @bosd  @ppsaheed @codeagencybe 

My apologies for the long time & thanks a lot for waiting for my response ❤️

**Review by yhaelopez — APPROVED** [review]

**Comment by bosd** [comment]
I'm glad your back! 
Hope you're well.

Maybe it is an idea to add more people with some powers to the organization. To make it less dependent on you as a single Individual.

**Comment by ppsaheed** [comment]
> After a long disappreance period (due to personal & professional matters) I'm getting back on track.
> I'll complete this integration and let you know @bosd  @ppsaheed @codeagencybe 
> 
> My apologies for the long time & thanks a lot for waiting for my response ❤️

We know you will be back 🤝

**Pull request merged**
